spring.application.name=spring-blog

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_blog
spring.datasource.username=vignesh
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.cors.allowed-origins=http://127.0.0.1:5173,http://localhost:5173
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allow-credentials=false
app.cors.max-age=3600

app.jwt.secret = 404e635266556a586e3272357538782f413f4428472b4b6250645367566b5970
app.jwt.expiration = 86400000

#spring.jpa.hibernate.ddl-auto=create

spring.liquibase.enabled=true
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml